name: Tarefa Diária

on:
  schedule:
    # Executa todos os dias à meia-noite (00:00 UTC)
    - cron: '10 00 * * *'
  workflow_dispatch:  # Permite executar manualmente o workflow

jobs:
  send-email:
    runs-on: ubuntu-latest  # Usando o Ubuntu como ambiente para execução

    steps:
    # Passo 1: Checkout do código
    - name: Checkout código
      uses: actions/checkout@v2

    # Passo 2: Configuração do ambiente Python
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use a versão do Python que você deseja

    # Passo 3: Instalar dependências (caso tenha algum pacote, como smtplib ou outros)
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        # Se tiver alguma dependência, adicione aqui, por exemplo:
        # pip install requests

    # Passo 4: Executar script Python (com o envio de e-mail)
    - name: Executar script Python
      run: |
        python script_data_padel.py
